apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: {{.Values.namespace.name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      name: techtrends
  template:
    metadata:
      labels:
        name: techtrends    
    spec:
      containers:
      - image: {{.Values.image.repository}}:{{.Values.image.tag}}
        imagePullPolicy: {{.Values.image.pullPolicy}}
        name: techtrends
        ports:
        - containerPort: 3111
          protocol: TCP
        livenessProbe:
          httpGet:
            path: {{.Values.livenessProbe.httpGet.path}}
            port: {{.Values.livenessProbe.httpGet.port}}
        readinessProbe:
          httpGet:
            path: {{.Values.readinessProbe.httpGet.path}}
            port: {{.Values.readinessProbe.httpGet.port}}
        resources:
          requests:
            cpu: "250m"           
            memory: "64Mi"       
          limits:
            cpu: "500m"           
            memory: "128Mi"
      imagePullSecrets:
        - name: regcred
           